echo "---\nlayout: default \nsearch: Acura\n--- \n {% include service-search.html%}">>sevice-Acura.html
echo "---\nlayout: default \nsearch: AlfaRomeo\n--- \n {% include service-search.html%}">>sevice-AlfaRomeo.html
echo "---\nlayout: default \nsearch: AstonMartin\n--- \n {% include service-search.html%}">>sevice-AstonMartin.html
echo "---\nlayout: default \nsearch: Audi\n--- \n {% include service-search.html%}">>sevice-Audi.html
echo "---\nlayout: default \nsearch: Bentley\n--- \n {% include service-search.html%}">>sevice-Bentley.html
echo "---\nlayout: default \nsearch: BMW\n--- \n {% include service-search.html%}">>sevice-BMW.html
echo "---\nlayout: default \nsearch: Brilliance\n--- \n {% include service-search.html%}">>sevice-Brilliance.html
echo "---\nlayout: default \nsearch: Bugatti\n--- \n {% include service-search.html%}">>sevice-Bugatti.html
echo "---\nlayout: default \nsearch: Buick\n--- \n {% include service-search.html%}">>sevice-Buick.html
echo "---\nlayout: default \nsearch: BYD\n--- \n {% include service-search.html%}">>sevice-BYD.html
echo "---\nlayout: default \nsearch: Cadillac\n--- \n {% include service-search.html%}">>sevice-Cadillac.html
echo "---\nlayout: default \nsearch: Changan\n--- \n {% include service-search.html%}">>sevice-Changan.html
echo "---\nlayout: default \nsearch: Chery\n--- \n {% include service-search.html%}">>sevice-Chery.html
echo "---\nlayout: default \nsearch: Chevrolet\n--- \n {% include service-search.html%}">>sevice-Chevrolet.html
echo "---\nlayout: default \nsearch: Chrysler\n--- \n {% include service-search.html%}">>sevice-Chrysler.html
echo "---\nlayout: default \nsearch: Citroen\n--- \n {% include service-search.html%}">>sevice-Citroen.html
echo "---\nlayout: default \nsearch: Daewoo\n--- \n {% include service-search.html%}">>sevice-Daewoo.html
echo "---\nlayout: default \nsearch: Daihatsu\n--- \n {% include service-search.html%}">>sevice-Daihatsu.html
echo "---\nlayout: default \nsearch: Datsun\n--- \n {% include service-search.html%}">>sevice-Datsun.html
echo "---\nlayout: default \nsearch: Dodge\n--- \n {% include service-search.html%}">>sevice-Dodge.html
echo "---\nlayout: default \nsearch: DongFeng\n--- \n {% include service-search.html%}">>sevice-DongFeng.html
echo "---\nlayout: default \nsearch: DS\n--- \n {% include service-search.html%}">>sevice-DS.html
echo "---\nlayout: default \nsearch: FAW\n--- \n {% include service-search.html%}">>sevice-FAW.html
echo "---\nlayout: default \nsearch: Ferrari\n--- \n {% include service-search.html%}">>sevice-Ferrari.html
echo "---\nlayout: default \nsearch: Fiat\n--- \n {% include service-search.html%}">>sevice-Fiat.html
echo "---\nlayout: default \nsearch: Ford\n--- \n {% include service-search.html%}">>sevice-Ford.html
echo "---\nlayout: default \nsearch: Foton\n--- \n {% include service-search.html%}">>sevice-Foton.html
echo "---\nlayout: default \nsearch: GAC\n--- \n {% include service-search.html%}">>sevice-GAC.html
echo "---\nlayout: default \nsearch: Geely\n--- \n {% include service-search.html%}">>sevice-Geely.html
echo "---\nlayout: default \nsearch: Genesis\n--- \n {% include service-search.html%}">>sevice-Genesis.html
echo "---\nlayout: default \nsearch: GMC\n--- \n {% include service-search.html%}">>sevice-GMC.html
echo "---\nlayout: default \nsearch: GreatWll\n--- \n {% include service-search.html%}">>sevice-GreatWll.html
echo "---\nlayout: default \nsearch: Haima\n--- \n {% include service-search.html%}">>sevice-Haima.html
echo "---\nlayout: default \nsearch: Haval\n--- \n {% include service-search.html%}">>sevice-Haval.html
echo "---\nlayout: default \nsearch: Honda\n--- \n {% include service-search.html%}">>sevice-Honda.html
echo "---\nlayout: default \nsearch: Hummer\n--- \n {% include service-search.html%}">>sevice-Hummer.html
echo "---\nlayout: default \nsearch: Hyundai\n--- \n {% include service-search.html%}">>sevice-Hyundai.html
echo "---\nlayout: default \nsearch: Infiniti\n--- \n {% include service-search.html%}">>sevice-Infiniti.html
echo "---\nlayout: default \nsearch: Isuzu\n--- \n {% include service-search.html%}">>sevice-Isuzu.html
echo "---\nlayout: default \nsearch: JAC\n--- \n {% include service-search.html%}">>sevice-JAC.html
echo "---\nlayout: default \nsearch: Jaguar\n--- \n {% include service-search.html%}">>sevice-Jaguar.html
echo "---\nlayout: default \nsearch: Jeep\n--- \n {% include service-search.html%}">>sevice-Jeep.html
echo "---\nlayout: default \nsearch: Kia\n--- \n {% include service-search.html%}">>sevice-Kia.html
echo "---\nlayout: default \nsearch: Lamborghini\n--- \n {% include service-search.html%}">>sevice-Lamborghini.html
echo "---\nlayout: default \nsearch: Lancia\n--- \n {% include service-search.html%}">>sevice-Lancia.html
echo "---\nlayout: default \nsearch: LandRover\n--- \n {% include service-search.html%}">>sevice-LandRover.html
echo "---\nlayout: default \nsearch: Lexus\n--- \n {% include service-search.html%}">>sevice-Lexus.html
echo "---\nlayout: default \nsearch: Lifan\n--- \n {% include service-search.html%}">>sevice-Lifan.html
echo "---\nlayout: default \nsearch: Lincoln\n--- \n {% include service-search.html%}">>sevice-Lincoln.html
echo "---\nlayout: default \nsearch: Luxgen\n--- \n {% include service-search.html%}">>sevice-Luxgen.html
echo "---\nlayout: default \nsearch: Maserati\n--- \n {% include service-search.html%}">>sevice-Maserati.html
echo "---\nlayout: default \nsearch: Maybach\n--- \n {% include service-search.html%}">>sevice-Maybach.html
echo "---\nlayout: default \nsearch: Mazda\n--- \n {% include service-search.html%}">>sevice-Mazda.html
echo "---\nlayout: default \nsearch: Mercedes\n--- \n {% include service-search.html%}">>sevice-Mercedes.html
echo "---\nlayout: default \nsearch: Mercury\n--- \n {% include service-search.html%}">>sevice-Mercury.html
echo "---\nlayout: default \nsearch: Mini\n--- \n {% include service-search.html%}">>sevice-Mini.html
echo "---\nlayout: default \nsearch: Mitsubishi\n--- \n {% include service-search.html%}">>sevice-Mitsubishi.html
echo "---\nlayout: default \nsearch: Nissan\n--- \n {% include service-search.html%}">>sevice-Nissan.html
echo "---\nlayout: default \nsearch: Oldsmobile\n--- \n {% include service-search.html%}">>sevice-Oldsmobile.html
echo "---\nlayout: default \nsearch: Opel\n--- \n {% include service-search.html%}">>sevice-Opel.html
echo "---\nlayout: default \nsearch: Peugeot\n--- \n {% include service-search.html%}">>sevice-Peugeot.html
echo "---\nlayout: default \nsearch: Pontiac\n--- \n {% include service-search.html%}">>sevice-Pontiac.html
echo "---\nlayout: default \nsearch: Porsche\n--- \n {% include service-search.html%}">>sevice-Porsche.html
echo "---\nlayout: default \nsearch: Ravon\n--- \n {% include service-search.html%}">>sevice-Ravon.html
echo "---\nlayout: default \nsearch: Renault\n--- \n {% include service-search.html%}">>sevice-Renault.html
echo "---\nlayout: default \nsearch: RollsRoyce\n--- \n {% include service-search.html%}">>sevice-RollsRoyce.html
echo "---\nlayout: default \nsearch: Rover\n--- \n {% include service-search.html%}">>sevice-Rover.html
echo "---\nlayout: default \nsearch: Saab\n--- \n {% include service-search.html%}">>sevice-Saab.html
echo "---\nlayout: default \nsearch: Scion\n--- \n {% include service-search.html%}">>sevice-Scion.html
echo "---\nlayout: default \nsearch: SEAT\n--- \n {% include service-search.html%}">>sevice-SEAT.html
echo "---\nlayout: default \nsearch: Skoda\n--- \n {% include service-search.html%}">>sevice-Skoda.html
echo "---\nlayout: default \nsearch: Smart\n--- \n {% include service-search.html%}">>sevice-Smart.html
echo "---\nlayout: default \nsearch: SsangYong\n--- \n {% include service-search.html%}">>sevice-SsangYong.html
echo "---\nlayout: default \nsearch: Subaru\n--- \n {% include service-search.html%}">>sevice-Subaru.html
echo "---\nlayout: default \nsearch: Suzuki\n--- \n {% include service-search.html%}">>sevice-Suzuki.html
echo "---\nlayout: default \nsearch: Tesla\n--- \n {% include service-search.html%}">>sevice-Tesla.html
echo "---\nlayout: default \nsearch: Toyota\n--- \n {% include service-search.html%}">>sevice-Toyota.html
echo "---\nlayout: default \nsearch: Volkswagen\n--- \n {% include service-search.html%}">>sevice-Volkswagen.html
echo "---\nlayout: default \nsearch: Volvo\n--- \n {% include service-search.html%}">>sevice-Volvo.html
echo "---\nlayout: default \nsearch: ZAZ\n--- \n {% include service-search.html%}">>sevice-ZAZ.html
echo "---\nlayout: default \nsearch: Zotye\n--- \n {% include service-search.html%}">>sevice-Zotye.html
echo "---\nlayout: default \nsearch: VAZ\n--- \n {% include service-search.html%}">>sevice-VAZ.html
echo "---\nlayout: default \nsearch: GAZ\n--- \n {% include service-search.html%}">>sevice-GAZ.html
echo "---\nlayout: default \nsearch: Moskvich\n--- \n {% include service-search.html%}">>sevice-Moskvich.html
echo "---\nlayout: default \nsearch: Tagaz\n--- \n {% include service-search.html%}">>sevice-Tagaz.html
echo "---\nlayout: default \nsearch: UAZ\n--- \n {% include service-search.html%}">>sevice-UAZ.html