echo "---\nlayout: default \nsearch: Acura\n--- \n {% include service-search.html%}">>service-Acura.html
echo "---\nlayout: default \nsearch: AlfaRomeo\n--- \n {% include service-search.html%}">>service-AlfaRomeo.html
echo "---\nlayout: default \nsearch: AstonMartin\n--- \n {% include service-search.html%}">>service-AstonMartin.html
echo "---\nlayout: default \nsearch: Audi\n--- \n {% include service-search.html%}">>service-Audi.html
echo "---\nlayout: default \nsearch: Bentley\n--- \n {% include service-search.html%}">>service-Bentley.html
echo "---\nlayout: default \nsearch: BMW\n--- \n {% include service-search.html%}">>service-BMW.html
echo "---\nlayout: default \nsearch: Brilliance\n--- \n {% include service-search.html%}">>service-Brilliance.html
echo "---\nlayout: default \nsearch: Bugatti\n--- \n {% include service-search.html%}">>service-Bugatti.html
echo "---\nlayout: default \nsearch: Buick\n--- \n {% include service-search.html%}">>service-Buick.html
echo "---\nlayout: default \nsearch: BYD\n--- \n {% include service-search.html%}">>service-BYD.html
echo "---\nlayout: default \nsearch: Cadillac\n--- \n {% include service-search.html%}">>service-Cadillac.html
echo "---\nlayout: default \nsearch: Changan\n--- \n {% include service-search.html%}">>service-Changan.html
echo "---\nlayout: default \nsearch: Chery\n--- \n {% include service-search.html%}">>service-Chery.html
echo "---\nlayout: default \nsearch: Chevrolet\n--- \n {% include service-search.html%}">>service-Chevrolet.html
echo "---\nlayout: default \nsearch: Chrysler\n--- \n {% include service-search.html%}">>service-Chrysler.html
echo "---\nlayout: default \nsearch: Citroen\n--- \n {% include service-search.html%}">>service-Citroen.html
echo "---\nlayout: default \nsearch: Daewoo\n--- \n {% include service-search.html%}">>service-Daewoo.html
echo "---\nlayout: default \nsearch: Daihatsu\n--- \n {% include service-search.html%}">>service-Daihatsu.html
echo "---\nlayout: default \nsearch: Datsun\n--- \n {% include service-search.html%}">>service-Datsun.html
echo "---\nlayout: default \nsearch: Dodge\n--- \n {% include service-search.html%}">>service-Dodge.html
echo "---\nlayout: default \nsearch: DongFeng\n--- \n {% include service-search.html%}">>service-DongFeng.html
echo "---\nlayout: default \nsearch: DS\n--- \n {% include service-search.html%}">>service-DS.html
echo "---\nlayout: default \nsearch: FAW\n--- \n {% include service-search.html%}">>service-FAW.html
echo "---\nlayout: default \nsearch: Ferrari\n--- \n {% include service-search.html%}">>service-Ferrari.html
echo "---\nlayout: default \nsearch: Fiat\n--- \n {% include service-search.html%}">>service-Fiat.html
echo "---\nlayout: default \nsearch: Ford\n--- \n {% include service-search.html%}">>service-Ford.html
echo "---\nlayout: default \nsearch: Foton\n--- \n {% include service-search.html%}">>service-Foton.html
echo "---\nlayout: default \nsearch: GAC\n--- \n {% include service-search.html%}">>service-GAC.html
echo "---\nlayout: default \nsearch: Geely\n--- \n {% include service-search.html%}">>service-Geely.html
echo "---\nlayout: default \nsearch: Genesis\n--- \n {% include service-search.html%}">>service-Genesis.html
echo "---\nlayout: default \nsearch: GMC\n--- \n {% include service-search.html%}">>service-GMC.html
echo "---\nlayout: default \nsearch: GreatWll\n--- \n {% include service-search.html%}">>service-GreatWll.html
echo "---\nlayout: default \nsearch: Haima\n--- \n {% include service-search.html%}">>service-Haima.html
echo "---\nlayout: default \nsearch: Haval\n--- \n {% include service-search.html%}">>service-Haval.html
echo "---\nlayout: default \nsearch: Honda\n--- \n {% include service-search.html%}">>service-Honda.html
echo "---\nlayout: default \nsearch: Hummer\n--- \n {% include service-search.html%}">>service-Hummer.html
echo "---\nlayout: default \nsearch: Hyundai\n--- \n {% include service-search.html%}">>service-Hyundai.html
echo "---\nlayout: default \nsearch: Infiniti\n--- \n {% include service-search.html%}">>service-Infiniti.html
echo "---\nlayout: default \nsearch: Isuzu\n--- \n {% include service-search.html%}">>service-Isuzu.html
echo "---\nlayout: default \nsearch: JAC\n--- \n {% include service-search.html%}">>service-JAC.html
echo "---\nlayout: default \nsearch: Jaguar\n--- \n {% include service-search.html%}">>service-Jaguar.html
echo "---\nlayout: default \nsearch: Jeep\n--- \n {% include service-search.html%}">>service-Jeep.html
echo "---\nlayout: default \nsearch: Kia\n--- \n {% include service-search.html%}">>service-Kia.html
echo "---\nlayout: default \nsearch: Lamborghini\n--- \n {% include service-search.html%}">>service-Lamborghini.html
echo "---\nlayout: default \nsearch: Lancia\n--- \n {% include service-search.html%}">>service-Lancia.html
echo "---\nlayout: default \nsearch: LandRover\n--- \n {% include service-search.html%}">>service-LandRover.html
echo "---\nlayout: default \nsearch: Lexus\n--- \n {% include service-search.html%}">>service-Lexus.html
echo "---\nlayout: default \nsearch: Lifan\n--- \n {% include service-search.html%}">>service-Lifan.html
echo "---\nlayout: default \nsearch: Lincoln\n--- \n {% include service-search.html%}">>service-Lincoln.html
echo "---\nlayout: default \nsearch: Luxgen\n--- \n {% include service-search.html%}">>service-Luxgen.html
echo "---\nlayout: default \nsearch: Maserati\n--- \n {% include service-search.html%}">>service-Maserati.html
echo "---\nlayout: default \nsearch: Maybach\n--- \n {% include service-search.html%}">>service-Maybach.html
echo "---\nlayout: default \nsearch: Mazda\n--- \n {% include service-search.html%}">>service-Mazda.html
echo "---\nlayout: default \nsearch: Mercedes\n--- \n {% include service-search.html%}">>service-Mercedes.html
echo "---\nlayout: default \nsearch: Mercury\n--- \n {% include service-search.html%}">>service-Mercury.html
echo "---\nlayout: default \nsearch: Mini\n--- \n {% include service-search.html%}">>service-Mini.html
echo "---\nlayout: default \nsearch: Mitsubishi\n--- \n {% include service-search.html%}">>service-Mitsubishi.html
echo "---\nlayout: default \nsearch: Nissan\n--- \n {% include service-search.html%}">>service-Nissan.html
echo "---\nlayout: default \nsearch: Oldsmobile\n--- \n {% include service-search.html%}">>service-Oldsmobile.html
echo "---\nlayout: default \nsearch: Opel\n--- \n {% include service-search.html%}">>service-Opel.html
echo "---\nlayout: default \nsearch: Peugeot\n--- \n {% include service-search.html%}">>service-Peugeot.html
echo "---\nlayout: default \nsearch: Pontiac\n--- \n {% include service-search.html%}">>service-Pontiac.html
echo "---\nlayout: default \nsearch: Porsche\n--- \n {% include service-search.html%}">>service-Porsche.html
echo "---\nlayout: default \nsearch: Ravon\n--- \n {% include service-search.html%}">>service-Ravon.html
echo "---\nlayout: default \nsearch: Renault\n--- \n {% include service-search.html%}">>service-Renault.html
echo "---\nlayout: default \nsearch: RollsRoyce\n--- \n {% include service-search.html%}">>service-RollsRoyce.html
echo "---\nlayout: default \nsearch: Rover\n--- \n {% include service-search.html%}">>service-Rover.html
echo "---\nlayout: default \nsearch: Saab\n--- \n {% include service-search.html%}">>service-Saab.html
echo "---\nlayout: default \nsearch: Scion\n--- \n {% include service-search.html%}">>service-Scion.html
echo "---\nlayout: default \nsearch: SEAT\n--- \n {% include service-search.html%}">>service-SEAT.html
echo "---\nlayout: default \nsearch: Skoda\n--- \n {% include service-search.html%}">>service-Skoda.html
echo "---\nlayout: default \nsearch: Smart\n--- \n {% include service-search.html%}">>service-Smart.html
echo "---\nlayout: default \nsearch: SsangYong\n--- \n {% include service-search.html%}">>service-SsangYong.html
echo "---\nlayout: default \nsearch: Subaru\n--- \n {% include service-search.html%}">>service-Subaru.html
echo "---\nlayout: default \nsearch: Suzuki\n--- \n {% include service-search.html%}">>service-Suzuki.html
echo "---\nlayout: default \nsearch: Tesla\n--- \n {% include service-search.html%}">>service-Tesla.html
echo "---\nlayout: default \nsearch: Toyota\n--- \n {% include service-search.html%}">>service-Toyota.html
echo "---\nlayout: default \nsearch: Volkswagen\n--- \n {% include service-search.html%}">>service-Volkswagen.html
echo "---\nlayout: default \nsearch: Volvo\n--- \n {% include service-search.html%}">>service-Volvo.html
echo "---\nlayout: default \nsearch: ZAZ\n--- \n {% include service-search.html%}">>service-ZAZ.html
echo "---\nlayout: default \nsearch: Zotye\n--- \n {% include service-search.html%}">>service-Zotye.html
echo "---\nlayout: default \nsearch: VAZ\n--- \n {% include service-search.html%}">>service-VAZ.html
echo "---\nlayout: default \nsearch: GAZ\n--- \n {% include service-search.html%}">>service-GAZ.html
echo "---\nlayout: default \nsearch: Moskvich\n--- \n {% include service-search.html%}">>service-Moskvich.html
echo "---\nlayout: default \nsearch: Tagaz\n--- \n {% include service-search.html%}">>service-Tagaz.html
echo "---\nlayout: default \nsearch: UAZ\n--- \n {% include service-search.html%}">>service-UAZ.html