echo "---\nlayout: service\nid: 0\n---">> Avtodrom\-S68.md
echo "---\nlayout: service\nid: 1\n---">> AvtoMaks\-S90.md
echo "---\nlayout: service\nid: 2\n---">> Avtomojka_na_Koptevskoj_73a\-S186.md
echo "---\nlayout: service\nid: 3\n---">> A_\&_Ja\-S1039.md
echo "---\nlayout: service\nid: 4\n---">> AAA_Smart\-S1040.md
echo "---\nlayout: service\nid: 5\n---">> ABIKAR\-S1041.md
echo "---\nlayout: service\nid: 6\n---">> Abris\-Ama\-S1042.md
echo "---\nlayout: service\nid: 7\n---">> SG\-Motors_na_Jugo\-Zapade\-S1043.md
echo "---\nlayout: service\nid: 8\n---">> SG\-Motors_na_VDNH\-S1044.md
echo "---\nlayout: service\nid: 9\n---">> ABSOLJuT\-S1045.md
echo "---\nlayout: service\nid: 10\n---">> ABS\-Motors\-S1046.md
echo "---\nlayout: service\nid: 11\n---">> Avalon\-S1047.md
echo "---\nlayout: service\nid: 12\n---">> Avangard\-S1048.md
echo "---\nlayout: service\nid: 13\n---">> Avanti_Motorc\-S1049.md
echo "---\nlayout: service\nid: 14\n---">> Avatar\-S1050.md
echo "---\nlayout: service\nid: 15\n---">> AVD_servis\-S1051.md
echo "---\nlayout: service\nid: 16\n---">> Avers_XXI\-S1052.md
echo "---\nlayout: service\nid: 17\n---">> Avrora\-S1053.md
echo "---\nlayout: service\nid: 18\n---">> Avto_Gaz\-S1054.md
echo "---\nlayout: service\nid: 19\n---">> Avto_globus\-S1055.md
echo "---\nlayout: service\nid: 20\n---">> Avto_Grand\-S1056.md
echo "---\nlayout: service\nid: 21\n---">> Avto_Djel\-S1057.md
echo "---\nlayout: service\nid: 22\n---">> Avto_Leon_Art\-S1058.md
echo "---\nlayout: service\nid: 23\n---">> Avto_Lider_OOO\-S1059.md
echo "---\nlayout: service\nid: 24\n---">> Avto_Prestizh\-S1060.md
echo "---\nlayout: service\nid: 25\n---">> Avto_Randevu\-S1061.md
echo "---\nlayout: service\nid: 26\n---">> Avto_spec_pomoshh_OOO\-S1062.md
echo "---\nlayout: service\nid: 27\n---">> Avto_Status\-S1063.md
echo "---\nlayout: service\nid: 28\n---">> AVTO_TehKompleks_OOO\-S1064.md
echo "---\nlayout: service\nid: 29\n---">> Avto_Shik\-S1065.md
echo "---\nlayout: service\nid: 30\n---">> Avto_7777\-S1066.md
echo "---\nlayout: service\nid: 31\n---">> AvtoAljansVostok\-S1067.md
echo "---\nlayout: service\nid: 32\n---">> Avtoaljans\-S1068.md
echo "---\nlayout: service\nid: 33\n---">> Avtoban\-Motors\-S1069.md
echo "---\nlayout: service\nid: 34\n---">> AvtoBoks\-S1070.md
echo "---\nlayout: service\nid: 35\n---">> Avtobot\-S1071.md
echo "---\nlayout: service\nid: 36\n---">> Avtobumer\-S1072.md
echo "---\nlayout: service\nid: 37\n---">> AVTOBUNKER\-S1073.md
echo "---\nlayout: service\nid: 38\n---">> Avtovelt\-motors\-S1074.md
echo "---\nlayout: service\nid: 39\n---">> Avtovest\-Servis\-S1075.md
echo "---\nlayout: service\nid: 40\n---">> AvtoVirazh\-S1076.md
echo "---\nlayout: service\nid: 41\n---">> AvtoVito\-Zapad\-S1077.md
echo "---\nlayout: service\nid: 42\n---">> AvtoVito\-Jug\-S1078.md
echo "---\nlayout: service\nid: 43\n---">> AvtoVito\-Butovo\-S1079.md
echo "---\nlayout: service\nid: 44\n---">> AvtoVi\-S1080.md
echo "---\nlayout: service\nid: 45\n---">> Avtogidrosistemy\-S1081.md
echo "---\nlayout: service\nid: 46\n---">> AVTOGLOBUS\-S1082.md
echo "---\nlayout: service\nid: 47\n---">> Avtogran\-S1083.md
echo "---\nlayout: service\nid: 48\n---">> AVTOGROVER\-S1084.md
echo "---\nlayout: service\nid: 49\n---">> Avtodar\-S1085.md
echo "---\nlayout: service\nid: 50\n---">> Avtodar\-servis\-S1086.md
echo "---\nlayout: service\nid: 51\n---">> AvtoDa\-S1087.md
echo "---\nlayout: service\nid: 52\n---">> Avtodeloff\-S1088.md
echo "---\nlayout: service\nid: 53\n---">> AvtoDiagnost\-S1090.md
echo "---\nlayout: service\nid: 54\n---">> AvtoDizajn\-S1091.md
echo "---\nlayout: service\nid: 55\n---">> Avtodizajn\-S1092.md
echo "---\nlayout: service\nid: 56\n---">> AVTODOKTOR\-S1093.md
echo "---\nlayout: service\nid: 57\n---">> Avtodok\-S1094.md
echo "---\nlayout: service\nid: 58\n---">> Avtodok\-S1095.md
echo "---\nlayout: service\nid: 59\n---">> Avtodok\-S1096.md
echo "---\nlayout: service\nid: 60\n---">> AvtoDok\-S\-S1097.md
echo "---\nlayout: service\nid: 61\n---">> AVTODOR\-S1098.md
echo "---\nlayout: service\nid: 62\n---">> Avtozashhita\-S1099.md
echo "---\nlayout: service\nid: 63\n---">> Avtokarat\-S1100.md
echo "---\nlayout: service\nid: 64\n---">> Avtoklever\-S1101.md
echo "---\nlayout: service\nid: 65\n---">> Avtoklub_8\-S1102.md
echo "---\nlayout: service\nid: 66\n---">> AvtoKlub\-S1103.md
echo "---\nlayout: service\nid: 67\n---">> Avtokompleks_na_ul_Kirova_19_st1\-S1104.md
echo "---\nlayout: service\nid: 68\n---">> Avtokredo_Pljus\-S1105.md
echo "---\nlayout: service\nid: 69\n---">> AVTOKRUG\-S1106.md
echo "---\nlayout: service\nid: 70\n---">> Avtokuzov\+\-S1107.md
echo "---\nlayout: service\nid: 71\n---">> Avtolegion\-S1108.md
echo "---\nlayout: service\nid: 72\n---">> AVTOLEKS\-S1109.md
echo "---\nlayout: service\nid: 73\n---">> Avtolik\-S1110.md
echo "---\nlayout: service\nid: 74\n---">> AvtoLjuks\-S1111.md
echo "---\nlayout: service\nid: 75\n---">> Avtoljuks\-Ronam\-S1112.md
echo "---\nlayout: service\nid: 76\n---">> Avtomagnat\-S1113.md
echo "---\nlayout: service\nid: 77\n---">> Avtomaksimum\-S1114.md
echo "---\nlayout: service\nid: 78\n---">> AvtoMaks\-S1115.md
echo "---\nlayout: service\nid: 79\n---">> AvtoMaks\-S1116.md
echo "---\nlayout: service\nid: 80\n---">> Avtomanija24\-S1117.md
echo "---\nlayout: service\nid: 81\n---">> Avtomarket_2000\-S1118.md
echo "---\nlayout: service\nid: 82\n---">> Avtomasterskaja_na_ul_Vatutina_2\-S1119.md
echo "---\nlayout: service\nid: 83\n---">> Avtomasterskaja_na_ul_Stepana_Razina_7_st1\-S1120.md
echo "---\nlayout: service\nid: 84\n---">> Avtomasterskaja_na_Urzhumskoj_3_st2\-S1121.md
echo "---\nlayout: service\nid: 85\n---">> Avtomaster\-S1122.md
echo "---\nlayout: service\nid: 86\n---">> Avtomaster\-S1123.md
echo "---\nlayout: service\nid: 87\n---">> Avtomaster\-S1124.md
echo "---\nlayout: service\nid: 88\n---">> Avtomaster\-14\-S1125.md
echo "---\nlayout: service\nid: 89\n---">> Avtomehanika\-dzhip\-S1126.md
echo "---\nlayout: service\nid: 90\n---">> Avtomehanik\-S1127.md
echo "---\nlayout: service\nid: 91\n---">> Avtomir_2000\-S1128.md
echo "---\nlayout: service\nid: 92\n---">> Avtomir\-S1129.md
echo "---\nlayout: service\nid: 93\n---">> AvtoMytishhi_OOO\-S1130.md
echo "---\nlayout: service\nid: 94\n---">> AVTONAVTIKA\-S1131.md
echo "---\nlayout: service\nid: 95\n---">> AVTONOM\-S1132.md
echo "---\nlayout: service\nid: 96\n---">> AVTOPARITET\-S1133.md
echo "---\nlayout: service\nid: 97\n---">> Avtopark\-S1134.md
echo "---\nlayout: service\nid: 98\n---">> AVTOPEGAS\-21\-S1135.md
